version: "3.9"

services:
  tdd-spring-boot-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: tdd-spring-boot:latest
    container_name: tdd-spring-boot
    ports:
      - "8081:8081"
    environment:
      - SERVER_PORT=8081
    networks:
      - quiz-application_cicd
    restart: always

networks:
  quiz-application_cicd:
    external: true
